name: Build and Deploy Java App

on:
  push:
    branches:
      - master
      - test-ci
  pull_request:
    branches:
      - master
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Authentication to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

#      - name: Configure Docker to use Artifact Registry
#        run: |
#          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: noc/spring-ai-mcp:latest